/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package burger;


import java.awt.event.KeyEvent;
import javax.swing.JFrame;
import javax.swing.JOptionPane;


/**
 *
 * @author AndresCangri
 */
public class Burger extends javax.swing.JFrame {

    //Precio de cada producto 
    double Precio_SalsaKetchup = 0.5;
    double Precio_SalsaBarbacoa = 0.5;
    double Precio_SalsaMostaza = 0.5;
    double Precio_SalsaThai = 0.5;
    double costeUnitarioSalsas;
    double iva = 21;
    double descuento=20;
    double pIva, pTotal, pSubtotal, pDescuento, pTotalDescuento, pEfectivo, pCambioDescuento;

    double[] costeSalsas = new double[4]; //Array que contiene las salsas

    /**
     * Creates new form Burger
     */
    public Burger() {
        initComponents();
        
    }
    
    //Icono del JFrame
    //como vamos a sobreescribir un método vamos a utilizar la palabra reservada @Override


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupCarne = new javax.swing.ButtonGroup();
        buttonGroupPan = new javax.swing.ButtonGroup();
        buttonGroupPatatas = new javax.swing.ButtonGroup();
        buttonGroupBebida = new javax.swing.ButtonGroup();
        jPanel6 = new javax.swing.JPanel();
        panelTitulo = new javax.swing.JPanel();
        labelTitulo = new javax.swing.JLabel();
        panelMenu = new javax.swing.JPanel();
        labelEslogan = new javax.swing.JLabel();
        labelCarne = new javax.swing.JLabel();
        labelPan = new javax.swing.JLabel();
        labelPatatas = new javax.swing.JLabel();
        labelBebida = new javax.swing.JLabel();
        btnPollo = new javax.swing.JRadioButton();
        btnCerdo = new javax.swing.JRadioButton();
        btnGajo = new javax.swing.JRadioButton();
        btnIntegral = new javax.swing.JRadioButton();
        btnTernera = new javax.swing.JRadioButton();
        btnFritas = new javax.swing.JRadioButton();
        btnCenteno = new javax.swing.JRadioButton();
        btnNomal = new javax.swing.JRadioButton();
        btnVegana = new javax.swing.JRadioButton();
        btnCola = new javax.swing.JRadioButton();
        btnLimon = new javax.swing.JRadioButton();
        btnCaseras = new javax.swing.JRadioButton();
        btnAgua = new javax.swing.JRadioButton();
        btnNaranja = new javax.swing.JRadioButton();
        btnCerveza = new javax.swing.JRadioButton();
        panelExtras = new javax.swing.JPanel();
        labelCompletaPedido = new javax.swing.JLabel();
        CheckBoxDoble = new javax.swing.JCheckBox();
        CheckBoxExtraQueso = new javax.swing.JCheckBox();
        CheckBoxExtraPatatas = new javax.swing.JCheckBox();
        panelSalsas = new javax.swing.JPanel();
        labelSalsas = new javax.swing.JLabel();
        CheckBoxKetchup = new javax.swing.JCheckBox();
        CheckBoxBarbacoa = new javax.swing.JCheckBox();
        CheckBoxMostaza = new javax.swing.JCheckBox();
        CheckBoxThai = new javax.swing.JCheckBox();
        campoSalsa2 = new javax.swing.JTextField();
        campoSalsa3 = new javax.swing.JTextField();
        campoSalsa4 = new javax.swing.JTextField();
        labelCosteAdicional = new javax.swing.JLabel();
        campoSalsa1 = new javax.swing.JTextField();
        panelPago = new javax.swing.JPanel();
        labelMetodoPago = new javax.swing.JLabel();
        ComboBoxPago = new javax.swing.JComboBox<>();
        campoEfectivo = new javax.swing.JTextField();
        CheckBoxRecogerPedido = new javax.swing.JCheckBox();
        labelDescuentoPedido = new javax.swing.JLabel();
        labelIva = new javax.swing.JLabel();
        labelSubTotal = new javax.swing.JLabel();
        labelDescuento = new javax.swing.JLabel();
        labelTotal = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        btnTotal = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        LabelIvaMenu = new javax.swing.JLabel();
        LabelTotalMenu = new javax.swing.JLabel();
        LabelSubTotalMenu = new javax.swing.JLabel();
        LabelDesuentoMenu = new javax.swing.JLabel();
        labelCambio = new javax.swing.JLabel();
        LabelCambioMenu = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(896, 626));

        jPanel6.setBackground(new java.awt.Color(204, 124, 85));
        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        panelTitulo.setBackground(new java.awt.Color(255, 102, 51));
        panelTitulo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        labelTitulo.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        labelTitulo.setText("BURGER");

        javax.swing.GroupLayout panelTituloLayout = new javax.swing.GroupLayout(panelTitulo);
        panelTitulo.setLayout(panelTituloLayout);
        panelTituloLayout.setHorizontalGroup(
            panelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTituloLayout.createSequentialGroup()
                .addGap(333, 333, 333)
                .addComponent(labelTitulo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelTituloLayout.setVerticalGroup(
            panelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTituloLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelTitulo)
                .addGap(16, 16, 16))
        );

        panelMenu.setBackground(new java.awt.Color(242, 203, 35));
        panelMenu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        panelMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        labelEslogan.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelEslogan.setText("Hola,¿Qué quieres comer hoy?");

        labelCarne.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labelCarne.setText("CARNE");

        labelPan.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labelPan.setText("PAN");

        labelPatatas.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labelPatatas.setText("PATATAS");

        labelBebida.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labelBebida.setText("BEBIDA");

        buttonGroupCarne.add(btnPollo);
        btnPollo.setSelected(true);
        btnPollo.setText("Pollo");
        btnPollo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPolloActionPerformed(evt);
            }
        });

        buttonGroupCarne.add(btnCerdo);
        btnCerdo.setText("Cerdo");

        buttonGroupPatatas.add(btnGajo);
        btnGajo.setText("Gajo");

        buttonGroupPan.add(btnIntegral);
        btnIntegral.setText("Integral");

        buttonGroupCarne.add(btnTernera);
        btnTernera.setText("Ternera +1$");

        buttonGroupPatatas.add(btnFritas);
        btnFritas.setSelected(true);
        btnFritas.setText("Fritas");

        buttonGroupPan.add(btnCenteno);
        btnCenteno.setText("Centeno");

        buttonGroupPan.add(btnNomal);
        btnNomal.setSelected(true);
        btnNomal.setText("Normal");

        buttonGroupCarne.add(btnVegana);
        btnVegana.setText("Vegana +1$");

        buttonGroupBebida.add(btnCola);
        btnCola.setSelected(true);
        btnCola.setText("Cola");

        buttonGroupBebida.add(btnLimon);
        btnLimon.setText("Limón ");
        btnLimon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimonActionPerformed(evt);
            }
        });

        buttonGroupPatatas.add(btnCaseras);
        btnCaseras.setText("Caseras +1$");

        buttonGroupBebida.add(btnAgua);
        btnAgua.setText("Agua");

        buttonGroupBebida.add(btnNaranja);
        btnNaranja.setText("Naranja");

        buttonGroupBebida.add(btnCerveza);
        btnCerveza.setText("Cerveza");
        btnCerveza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCervezaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelMenuLayout = new javax.swing.GroupLayout(panelMenu);
        panelMenu.setLayout(panelMenuLayout);
        panelMenuLayout.setHorizontalGroup(
            panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenuLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(labelEslogan)
                .addGap(92, 92, 92))
            .addGroup(panelMenuLayout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelMenuLayout.createSequentialGroup()
                        .addGroup(panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnTernera)
                            .addComponent(btnCerdo)
                            .addComponent(btnVegana)
                            .addComponent(btnPollo))
                        .addGap(163, 163, 163)
                        .addGroup(panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnIntegral)
                            .addComponent(btnNomal)
                            .addComponent(btnCenteno))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panelMenuLayout.createSequentialGroup()
                        .addComponent(labelCarne)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(labelPan)
                        .addGap(126, 126, 126)))
                .addGroup(panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelPatatas)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnCaseras)
                        .addComponent(btnGajo)
                        .addComponent(btnFritas)))
                .addGap(134, 134, 134)
                .addGroup(panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCerveza)
                    .addComponent(labelBebida)
                    .addComponent(btnCola)
                    .addComponent(btnNaranja)
                    .addComponent(btnLimon)
                    .addComponent(btnAgua))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelMenuLayout.setVerticalGroup(
            panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelEslogan)
                .addGap(29, 29, 29)
                .addGroup(panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCarne)
                    .addComponent(labelPan)
                    .addComponent(labelPatatas)
                    .addComponent(labelBebida))
                .addGap(28, 28, 28)
                .addGroup(panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPollo)
                    .addComponent(btnNomal)
                    .addComponent(btnFritas)
                    .addComponent(btnCola))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCerdo)
                    .addComponent(btnGajo)
                    .addComponent(btnNaranja)
                    .addComponent(btnCenteno))
                .addGap(7, 7, 7)
                .addGroup(panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTernera)
                    .addComponent(btnCaseras)
                    .addComponent(btnLimon)
                    .addComponent(btnIntegral))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgua)
                    .addComponent(btnVegana))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCerveza)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        panelExtras.setBackground(new java.awt.Color(218, 112, 74));
        panelExtras.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        panelExtras.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        labelCompletaPedido.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelCompletaPedido.setText("¡Completa tu pedido!");

        CheckBoxDoble.setText("Hamburguesa doble +2$");

        CheckBoxExtraQueso.setText("Extra de queso +0.50$");

        CheckBoxExtraPatatas.setText("Extra de patatas +1$");

        javax.swing.GroupLayout panelExtrasLayout = new javax.swing.GroupLayout(panelExtras);
        panelExtras.setLayout(panelExtrasLayout);
        panelExtrasLayout.setHorizontalGroup(
            panelExtrasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelExtrasLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(panelExtrasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CheckBoxExtraQueso)
                    .addComponent(CheckBoxDoble)
                    .addComponent(CheckBoxExtraPatatas))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelExtrasLayout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addComponent(labelCompletaPedido)
                .addGap(45, 45, 45))
        );
        panelExtrasLayout.setVerticalGroup(
            panelExtrasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelExtrasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelCompletaPedido)
                .addGap(27, 27, 27)
                .addComponent(CheckBoxDoble)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CheckBoxExtraQueso)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CheckBoxExtraPatatas)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelSalsas.setBackground(new java.awt.Color(218, 112, 74));
        panelSalsas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        panelSalsas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        labelSalsas.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelSalsas.setText("Salsas");

        CheckBoxKetchup.setText("Ketchup");
        CheckBoxKetchup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckBoxKetchupActionPerformed(evt);
            }
        });

        CheckBoxBarbacoa.setText("Barbacoa");
        CheckBoxBarbacoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckBoxBarbacoaActionPerformed(evt);
            }
        });

        CheckBoxMostaza.setText("Mostaza");
        CheckBoxMostaza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckBoxMostazaActionPerformed(evt);
            }
        });

        CheckBoxThai.setText("Thai");
        CheckBoxThai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckBoxThaiActionPerformed(evt);
            }
        });

        campoSalsa2.setText("0");
        campoSalsa2.setEnabled(false);
        campoSalsa2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoSalsa2ActionPerformed(evt);
            }
        });
        campoSalsa2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                campoSalsa2KeyTyped(evt);
            }
        });

        campoSalsa3.setText("0");
        campoSalsa3.setEnabled(false);
        campoSalsa3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoSalsa3ActionPerformed(evt);
            }
        });
        campoSalsa3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                campoSalsa3KeyTyped(evt);
            }
        });

        campoSalsa4.setText("0");
        campoSalsa4.setEnabled(false);
        campoSalsa4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoSalsa4ActionPerformed(evt);
            }
        });
        campoSalsa4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                campoSalsa4KeyTyped(evt);
            }
        });

        labelCosteAdicional.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        labelCosteAdicional.setText("*Cada salsa tendra un coste adicional de 0.5$/unidad");

        campoSalsa1.setBackground(new java.awt.Color(242, 242, 242));
        campoSalsa1.setText("0");
        campoSalsa1.setEnabled(false);
        campoSalsa1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoSalsa1ActionPerformed(evt);
            }
        });
        campoSalsa1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                campoSalsa1KeyTyped(evt);
            }
        });

        javax.swing.GroupLayout panelSalsasLayout = new javax.swing.GroupLayout(panelSalsas);
        panelSalsas.setLayout(panelSalsasLayout);
        panelSalsasLayout.setHorizontalGroup(
            panelSalsasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSalsasLayout.createSequentialGroup()
                .addGroup(panelSalsasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelSalsasLayout.createSequentialGroup()
                        .addGroup(panelSalsasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelSalsasLayout.createSequentialGroup()
                                .addGap(106, 106, 106)
                                .addComponent(labelSalsas))
                            .addGroup(panelSalsasLayout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addGroup(panelSalsasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(CheckBoxBarbacoa)
                                    .addComponent(CheckBoxKetchup)
                                    .addComponent(CheckBoxMostaza)
                                    .addComponent(CheckBoxThai))
                                .addGap(18, 18, 18)
                                .addGroup(panelSalsasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(campoSalsa2, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
                                    .addComponent(campoSalsa3)
                                    .addComponent(campoSalsa4)
                                    .addComponent(campoSalsa1))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelSalsasLayout.createSequentialGroup()
                        .addGap(0, 14, Short.MAX_VALUE)
                        .addComponent(labelCosteAdicional)))
                .addContainerGap())
        );
        panelSalsasLayout.setVerticalGroup(
            panelSalsasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSalsasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelSalsas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelSalsasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(CheckBoxKetchup)
                    .addComponent(campoSalsa1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelSalsasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CheckBoxBarbacoa)
                    .addComponent(campoSalsa2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelSalsasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CheckBoxMostaza)
                    .addComponent(campoSalsa3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelSalsasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CheckBoxThai)
                    .addComponent(campoSalsa4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(labelCosteAdicional)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelPago.setBackground(new java.awt.Color(218, 112, 74));
        panelPago.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        panelPago.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        labelMetodoPago.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelMetodoPago.setText("Método de Pago");

        ComboBoxPago.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Debit Card", "Cash" }));
        ComboBoxPago.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        ComboBoxPago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxPagoActionPerformed(evt);
            }
        });

        campoEfectivo.setText("0");
        campoEfectivo.setEnabled(false);
        campoEfectivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoEfectivoActionPerformed(evt);
            }
        });
        campoEfectivo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                campoEfectivoKeyTyped(evt);
            }
        });

        CheckBoxRecogerPedido.setText("Recoger Pedido");
        CheckBoxRecogerPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckBoxRecogerPedidoActionPerformed(evt);
            }
        });

        labelDescuentoPedido.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        labelDescuentoPedido.setText("*20% Descuento");

        labelIva.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelIva.setText("Iva 21%");

        labelSubTotal.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelSubTotal.setText("Sub Total");

        labelDescuento.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelDescuento.setText("Descuento");

        labelTotal.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelTotal.setText("Total");

        jSeparator1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnTotal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnTotal.setText("Total");
        btnTotal.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTotalActionPerformed(evt);
            }
        });

        btnReset.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnReset.setText("Reset");
        btnReset.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        btnExit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnExit.setText("Exit");
        btnExit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        LabelIvaMenu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        LabelTotalMenu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        LabelSubTotalMenu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        LabelDesuentoMenu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        labelCambio.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelCambio.setText("Cambio");

        LabelCambioMenu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout panelPagoLayout = new javax.swing.GroupLayout(panelPago);
        panelPago.setLayout(panelPagoLayout);
        panelPagoLayout.setHorizontalGroup(
            panelPagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPagoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelPagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelPagoLayout.createSequentialGroup()
                        .addGroup(panelPagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(labelMetodoPago, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(campoEfectivo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ComboBoxPago, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelPagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(labelDescuentoPedido)
                        .addComponent(CheckBoxRecogerPedido)
                        .addComponent(btnTotal)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelPagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelPagoLayout.createSequentialGroup()
                        .addComponent(btnReset)
                        .addGap(26, 26, 26)
                        .addComponent(btnExit)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(panelPagoLayout.createSequentialGroup()
                        .addGroup(panelPagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelIva)
                            .addComponent(labelSubTotal)
                            .addComponent(labelDescuento)
                            .addComponent(labelTotal)
                            .addComponent(labelCambio))
                        .addGap(24, 24, 24)
                        .addGroup(panelPagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LabelCambioMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LabelTotalMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LabelDesuentoMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LabelIvaMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LabelSubTotalMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(16, Short.MAX_VALUE))))
        );
        panelPagoLayout.setVerticalGroup(
            panelPagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPagoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelPagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelPagoLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(panelPagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(LabelSubTotalMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelSubTotal))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelPagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(LabelIvaMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelIva))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelPagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelDescuento, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(LabelDesuentoMenu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8)
                        .addGroup(panelPagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(labelTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(LabelTotalMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelPagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(labelCambio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(LabelCambioMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(panelPagoLayout.createSequentialGroup()
                        .addComponent(labelMetodoPago)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ComboBoxPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(campoEfectivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(CheckBoxRecogerPedido)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelDescuentoPedido))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(panelPagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTotal)
                    .addComponent(btnReset)
                    .addComponent(btnExit))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(panelTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(panelExtras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelSalsas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(17, 17, 17))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(panelExtras, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(panelSalsas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(panelPago, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 880, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLimonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLimonActionPerformed

    
    //Boto total, donde realizamos todas las operaciones 
    
    private void btnTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTotalActionPerformed
        // TODO add your handling code here:

        double precio = 8.00; //Precio básico del menú
        //Precio de cada extra en el que la forma de elegirlo es CheckBox
        //vamos aumentando el precio segun el usuario añada extras 
        if (btnTernera.isSelected()) {
            precio += 1;
        }
        if (btnVegana.isSelected()) {
            precio += 1;
        }
        if (btnCaseras.isSelected()) {
            precio += 1;
        }
        if (CheckBoxDoble.isSelected()) {
            precio += 2;
        }
        if (CheckBoxExtraQueso.isSelected()) {
            precio += 0.50;
        }
        if (CheckBoxExtraPatatas.isSelected()) {
            precio += 1;
        }

        //En el Array previamente creado en la parte de arriba, metemos los campos de las salsas 
        //ya que le hemos propuesta en esta ocasión que el usuario meta por teclado el numero de salsas que quiere
        costeSalsas[0] = Double.parseDouble(campoSalsa1.getText());
        costeSalsas[1] = Double.parseDouble(campoSalsa2.getText());
        costeSalsas[2] = Double.parseDouble(campoSalsa3.getText());
        costeSalsas[3] = Double.parseDouble(campoSalsa4.getText());
        //El string que recibe el cambio lo pasamos a un double 
        pEfectivo= Double.parseDouble(campoEfectivo.getText());
        String metodoDePago = (String)ComboBoxPago.getSelectedItem();
        
        if(metodoDePago == "Cash")
        {
        //Obtenemos el coste de todas las salsas
        costeUnitarioSalsas = costeSalsas[0] + costeSalsas[1] + costeSalsas[2] + costeSalsas[3];
        //Si el cambio es mayor o igual que el coste total procedemos hacer las operaciones 
        if(pEfectivo >= pTotal){
        //Sumanos el coste + el precios de las salsas
        pSubtotal = precio + costeUnitarioSalsas;
        //Sacamos el Iva
        pIva=(pSubtotal * iva)/100;
        //Sacamos el descuento
        pDescuento=(pSubtotal*descuento)/100;
        //Total sin descuento 
        pTotal=(pSubtotal + pIva);
        // El total del cambio menos el descuento por recogerlo
        //Sacamos el total menos el descuento 
        pTotalDescuento=(pTotal - pDescuento);
        //pCambioDescuento=(pCambio - pTotalDescuento);
        
       //Aqui como el resultado que obtenemos del  Subtotal, Iva, Descuento, Total es un double 
       //lo que hacemos es transformarlo en un string para pasarle al jLabel que le correspode.
        String formatopSubtotal = String.format("%.2f$", pSubtotal);
        LabelSubTotalMenu.setText(formatopSubtotal);
        String formatopIva = String.format("%.2f$", pIva);
        LabelIvaMenu.setText(formatopIva);
        String formatopTotal = String.format("%.2f$", pTotal);
        LabelTotalMenu.setText(formatopTotal);
        String formatoCambio = String.format("%.2f$", pEfectivo - pTotal);
        LabelCambioMenu.setText(formatoCambio);
         //Si el usuario elegie la opcion de recogerlo le aplicamos el descuento sobre el precio total 
        if(CheckBoxRecogerPedido.isSelected()){
            String formatopDescuento = String.format("%.2f$", pDescuento);
            LabelDesuentoMenu.setText(formatopDescuento);
            String formatopTotalDescuento = String.format("%.2f$", pTotalDescuento);
            LabelTotalMenu.setText(formatopTotalDescuento);
            String formatopCambioDescuento = String.format("%.2f$",pEfectivo - pTotalDescuento );
            LabelCambioMenu.setText(formatopCambioDescuento);
        }
        
        
        }
        else if (pEfectivo < pTotal){
            //this -> para que se quede centrado el aviso dentro de la interfaz, otra opción null
              JOptionPane.showMessageDialog(this, "El importe introducido es insuficiente", "Burger", JOptionPane.OK_OPTION);
        }
        
        }else if ("Debit Card".equals(metodoDePago)){//Si elegimos al opcion de Debit Card
        //Obtenemos el coste de todas las salsas
        costeUnitarioSalsas = costeSalsas[0] + costeSalsas[1] + costeSalsas[2] + costeSalsas[3];
        //Sumanos el coste + el precios de las salsas
        pSubtotal = precio + costeUnitarioSalsas;
        //Sacamos el Iva
        pIva=(pSubtotal * iva)/100;
        //Sacamos el descuento
        pDescuento=(pSubtotal*descuento)/100;
        //Sacamos el total con descuento
        pTotalDescuento=((pSubtotal + pIva) - pDescuento);
        //Sacamos el total sin descuento 
        pTotal=(pSubtotal + pIva);
       
        String formatopSubtotal = String.format("%.2f$", pSubtotal);
        LabelSubTotalMenu.setText(formatopSubtotal);
        String formatopIva = String.format("%.2f$", pIva);
        LabelIvaMenu.setText(formatopIva);
        String formatopTotal = String.format("%.2f$", pTotal);
        LabelTotalMenu.setText(formatopTotal);
        
        //Si el usuario elegie la opcion de recogerlo le aplicamos el descuento sobre el precio total 
        if(CheckBoxRecogerPedido.isSelected()){
            String formatopDescuento = String.format("%.2f$", pDescuento);
            LabelDesuentoMenu.setText(formatopDescuento);
            String formatopTotalDescuento = String.format("%.2f$", pTotalDescuento);
            LabelTotalMenu.setText(formatopTotalDescuento);
        }
        }
        
        

    }//GEN-LAST:event_btnTotalActionPerformed
    private JFrame frame; //llamamo al JFrame que lo utilizaremos abajo 
    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // Bóton de salir:
        frame = new JFrame("Salir"); //creamos el objeto JFrame el cual utilizaremos para salir
        //usamos un para que nos devuelva una venta donde nos pregunte que confirmemos que queremos salir, con un YES_NO_OPTION 
        if (JOptionPane.showConfirmDialog(frame, "Confirma que quieres salir", "BURGER", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_NO_OPTION) {
            System.exit(0);
        }

    }//GEN-LAST:event_btnExitActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // Botón de resetear:

        //Pasamos todos los valores de los campos que tiene nuestra interfaz a null
        campoSalsa1.setText("0");
        campoSalsa2.setText("0");
        campoSalsa3.setText("0");
        campoSalsa4.setText("0");
        campoEfectivo.setText("0");

        //Reseteamos los RadioButton que esta dentro de un grupo para eso llamámos al métodp  clearSelection() 
        //En el caso que el radioButtom no estuviera dentro de un grupo basta con  setState o setSelected
        buttonGroupCarne.clearSelection();
        buttonGroupPan.clearSelection();
        buttonGroupPatatas.clearSelection();
        buttonGroupBebida.clearSelection();
        btnPollo.setSelected(true);
        //Limpiamos los checkbox con setSelected()
        CheckBoxBarbacoa.setSelected(false);
        CheckBoxDoble.setSelected(false);
        CheckBoxExtraPatatas.setSelected(false);
        CheckBoxExtraQueso.setSelected(false);
        CheckBoxKetchup.setSelected(false);
        CheckBoxMostaza.setSelected(false);
        CheckBoxRecogerPedido.setSelected(false);
        CheckBoxThai.setSelected(false);
        
        //Limpiamos los Labels de nuestro panel de pago 
        LabelDesuentoMenu.setText("0");
        LabelIvaMenu.setText("0");
        LabelSubTotalMenu.setText("0");
        LabelTotalMenu.setText("0");
        LabelCambioMenu.setText("0"); 

    }//GEN-LAST:event_btnResetActionPerformed

    private void campoSalsa3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoSalsa3ActionPerformed
        // TODO add y:
    }//GEN-LAST:event_campoSalsa3ActionPerformed

    private void btnPolloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPolloActionPerformed
        // TODO add your handling code here:  
       
    }//GEN-LAST:event_btnPolloActionPerformed

    private void campoSalsa2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoSalsa2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoSalsa2ActionPerformed

    private void campoSalsa4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoSalsa4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoSalsa4ActionPerformed

    private void campoSalsa1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoSalsa1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoSalsa1ActionPerformed

    private void CheckBoxKetchupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckBoxKetchupActionPerformed
        // :
        if (CheckBoxKetchup.isSelected()) {
            campoSalsa1.setEnabled(true);
            campoSalsa1.requestFocus();
            campoSalsa1.setText("");
        } else {
            campoSalsa1.setEnabled(false);
            campoSalsa1.setText("0");
        }

    }//GEN-LAST:event_CheckBoxKetchupActionPerformed

    private void campoSalsa1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoSalsa1KeyTyped
        // Lo que vamos hacer es que cambiamos el event, de ActionEvent A KeyeEvent para poder fijar que solo se puedean 
        // meter numeros del teclado, asi nos aseguramos que no exista equivocaion al queremer meter por teclado nada que no sea números:

        char iNumero = evt.getKeyChar();
        if (!(Character.isDigit(iNumero))
                || (iNumero == KeyEvent.VK_BACK_SPACE)
                || (iNumero == KeyEvent.VK_DELETE)) {
            evt.consume();
        }
    }//GEN-LAST:event_campoSalsa1KeyTyped

    private void campoSalsa2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoSalsa2KeyTyped
        // TODO add your handling code here:
        char iNumero = evt.getKeyChar();
        if (!(Character.isDigit(iNumero))
                || (iNumero == KeyEvent.VK_BACK_SPACE)
                || (iNumero == KeyEvent.VK_DELETE)) {
            evt.consume();
        }

    }//GEN-LAST:event_campoSalsa2KeyTyped

    private void campoSalsa3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoSalsa3KeyTyped
        // TODO add your handling code here:

        char iNumero = evt.getKeyChar();
        if (!(Character.isDigit(iNumero))
                || (iNumero == KeyEvent.VK_BACK_SPACE)
                || (iNumero == KeyEvent.VK_DELETE)) {
            evt.consume();
        }
    }//GEN-LAST:event_campoSalsa3KeyTyped

    private void campoSalsa4KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoSalsa4KeyTyped
        // TODO add your handling code here:
        char iNumero = evt.getKeyChar();
        if (!(Character.isDigit(iNumero))
                || (iNumero == KeyEvent.VK_BACK_SPACE)
                || (iNumero == KeyEvent.VK_DELETE)) {
            evt.consume();
        }
    }//GEN-LAST:event_campoSalsa4KeyTyped

    private void campoEfectivoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoEfectivoKeyTyped
        // TODO add your handling code here:

    }//GEN-LAST:event_campoEfectivoKeyTyped

    private void CheckBoxBarbacoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckBoxBarbacoaActionPerformed
        // Cuando seleccionamos un CheckBox hacemos que el el label que en este caso es el campoSalsa2 
        // pase a estar disponible para meter datos dentro de este Label, si no lo seleccionamos no 
        //nos dejara ontroducir nada en el Label:
        if (CheckBoxBarbacoa.isSelected()) {
            campoSalsa2.setEnabled(true);
            // hacemos que el focus pase directamene al jLabel en cuanto selecionamos el checkBox 
            //evitamos que el usuario tenga que estar selecionando 
            campoSalsa2.requestFocus();
            //cuando lo selecionamos el checkBox el texto de nuestro label campoSalsa2 pasa a estar vacio 
            campoSalsa2.setText("");
        } else {
            campoSalsa2.setEnabled(false);// como no esta selecionado, queda bloqueado para el usuario
            campoSalsa2.setText("0"); // Le indicamos que mientras este bloqueado nos muestre "0"
        }
    }//GEN-LAST:event_CheckBoxBarbacoaActionPerformed

    private void CheckBoxMostazaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckBoxMostazaActionPerformed
        // TODO add your handling code here:
        if (CheckBoxMostaza.isSelected()) {
            campoSalsa3.setEnabled(true);
            campoSalsa3.requestFocus();
            campoSalsa3.setText("");
        } else {
            campoSalsa3.setEnabled(false);
            campoSalsa3.setText("0");
        }
    }//GEN-LAST:event_CheckBoxMostazaActionPerformed

    private void CheckBoxThaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckBoxThaiActionPerformed
        // TODO add your handling code here:
        if (CheckBoxThai.isSelected()) {
            campoSalsa4.setEnabled(true);
            campoSalsa4.requestFocus();
            campoSalsa4.setText("");
        } else {
            campoSalsa4.setEnabled(false);
            campoSalsa4.setText("0");
        }
    }//GEN-LAST:event_CheckBoxThaiActionPerformed

    private void CheckBoxRecogerPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckBoxRecogerPedidoActionPerformed
        // TODO add your handling code here:
      
    }//GEN-LAST:event_CheckBoxRecogerPedidoActionPerformed

    private void campoEfectivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoEfectivoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoEfectivoActionPerformed

    private void ComboBoxPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxPagoActionPerformed
        // ComboBox:
        //Lo que le decimos al programa es que si la opcion en el comboBox es igual a Debit 
        //el Label es disponible para introducir datos 
        //si no esta selecionada la opcion de pago en CASH, estara bloqueado
       String metodoDePago = (String)ComboBoxPago.getSelectedItem();
        if("Debit Card".equals(metodoDePago)) {
            campoEfectivo.setEnabled(false);
         
        } else {
            campoEfectivo.setEnabled(true);
            campoEfectivo.requestFocus();
        }
    }//GEN-LAST:event_ComboBoxPagoActionPerformed

    private void btnCervezaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCervezaActionPerformed
        // TODO add your handling code here:
        int i = JOptionPane.showConfirmDialog(this, "¿Eres mayor de edad?");
        if( i == 0){
            JOptionPane.showMessageDialog(this, "Gracias por confirmar que eres mayor de edad");
        } else if (i == 1){
            JOptionPane.showMessageDialog(this, "Debes de elegir otra opción");
            btnCerveza.setEnabled(false);
        }
        
    }//GEN-LAST:event_btnCervezaActionPerformed

    /**
     * @param args the command line arguments/
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Burger.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Burger.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Burger.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Burger.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Burger().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox CheckBoxBarbacoa;
    private javax.swing.JCheckBox CheckBoxDoble;
    private javax.swing.JCheckBox CheckBoxExtraPatatas;
    private javax.swing.JCheckBox CheckBoxExtraQueso;
    private javax.swing.JCheckBox CheckBoxKetchup;
    private javax.swing.JCheckBox CheckBoxMostaza;
    private javax.swing.JCheckBox CheckBoxRecogerPedido;
    private javax.swing.JCheckBox CheckBoxThai;
    private javax.swing.JComboBox<String> ComboBoxPago;
    private javax.swing.JLabel LabelCambioMenu;
    private javax.swing.JLabel LabelDesuentoMenu;
    private javax.swing.JLabel LabelIvaMenu;
    private javax.swing.JLabel LabelSubTotalMenu;
    private javax.swing.JLabel LabelTotalMenu;
    private javax.swing.JRadioButton btnAgua;
    private javax.swing.JRadioButton btnCaseras;
    private javax.swing.JRadioButton btnCenteno;
    private javax.swing.JRadioButton btnCerdo;
    private javax.swing.JRadioButton btnCerveza;
    private javax.swing.JRadioButton btnCola;
    private javax.swing.JButton btnExit;
    private javax.swing.JRadioButton btnFritas;
    private javax.swing.JRadioButton btnGajo;
    private javax.swing.JRadioButton btnIntegral;
    private javax.swing.JRadioButton btnLimon;
    private javax.swing.JRadioButton btnNaranja;
    private javax.swing.JRadioButton btnNomal;
    private javax.swing.JRadioButton btnPollo;
    private javax.swing.JButton btnReset;
    private javax.swing.JRadioButton btnTernera;
    private javax.swing.JButton btnTotal;
    private javax.swing.JRadioButton btnVegana;
    private javax.swing.ButtonGroup buttonGroupBebida;
    private javax.swing.ButtonGroup buttonGroupCarne;
    private javax.swing.ButtonGroup buttonGroupPan;
    private javax.swing.ButtonGroup buttonGroupPatatas;
    private javax.swing.JTextField campoEfectivo;
    private javax.swing.JTextField campoSalsa1;
    private javax.swing.JTextField campoSalsa2;
    private javax.swing.JTextField campoSalsa3;
    private javax.swing.JTextField campoSalsa4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel labelBebida;
    private javax.swing.JLabel labelCambio;
    private javax.swing.JLabel labelCarne;
    private javax.swing.JLabel labelCompletaPedido;
    private javax.swing.JLabel labelCosteAdicional;
    private javax.swing.JLabel labelDescuento;
    private javax.swing.JLabel labelDescuentoPedido;
    private javax.swing.JLabel labelEslogan;
    private javax.swing.JLabel labelIva;
    private javax.swing.JLabel labelMetodoPago;
    private javax.swing.JLabel labelPan;
    private javax.swing.JLabel labelPatatas;
    private javax.swing.JLabel labelSalsas;
    private javax.swing.JLabel labelSubTotal;
    private javax.swing.JLabel labelTitulo;
    private javax.swing.JLabel labelTotal;
    private javax.swing.JPanel panelExtras;
    private javax.swing.JPanel panelMenu;
    private javax.swing.JPanel panelPago;
    private javax.swing.JPanel panelSalsas;
    private javax.swing.JPanel panelTitulo;
    // End of variables declaration//GEN-END:variables
}
